./pngout "snail [www.imagesplitter.net]-0-0.gif" -c6
./pngout "snail [www.imagesplitter.net]-0-1.gif" -c6
./pngout "snail [www.imagesplitter.net]-0-2.gif" -c6
./pngout "snail [www.imagesplitter.net]-0-3.gif" -c6
./pngout "snail [www.imagesplitter.net]-0-4.gif" -c6
./pngout "snail [www.imagesplitter.net]-0-5.gif" -c6
./pngout "snail [www.imagesplitter.net]-0-6.gif" -c6
./pngout "snail [www.imagesplitter.net]-0-7.gif" -c6
./pngout "snail [www.imagesplitter.net]-0-8.gif" -c6
./pngout "snail [www.imagesplitter.net]-0-9.gif" -c6
./pngout "snail [www.imagesplitter.net]-1-0.gif" -c6
./pngout "snail [www.imagesplitter.net]-1-1.gif" -c6
./pngout "snail [www.imagesplitter.net]-1-2.gif" -c6
./pngout "snail [www.imagesplitter.net]-1-3.gif" -c6
./pngout "snail [www.imagesplitter.net]-1-4.gif" -c6
./pngout "snail [www.imagesplitter.net]-1-5.gif" -c6
./pngout "snail [www.imagesplitter.net]-1-6.gif" -c6
./pngout "snail [www.imagesplitter.net]-1-7.gif" -c6
./pngout "snail [www.imagesplitter.net]-1-8.gif" -c6
./pngout "snail [www.imagesplitter.net]-1-9.gif" -c6
./pngout "snail [www.imagesplitter.net]-2-0.gif" -c6
./pngout "snail [www.imagesplitter.net]-2-1.gif" -c6
./pngout "snail [www.imagesplitter.net]-2-2.gif" -c6
./pngout "snail [www.imagesplitter.net]-2-3.gif" -c6
./pngout "snail [www.imagesplitter.net]-2-4.gif" -c6
./pngout "snail [www.imagesplitter.net]-2-5.gif" -c6
./pngout "snail [www.imagesplitter.net]-2-6.gif" -c6
./pngout "snail [www.imagesplitter.net]-2-7.gif" -c6
./pngout "snail [www.imagesplitter.net]-2-8.gif" -c6
./pngout "snail [www.imagesplitter.net]-2-9.gif" -c6

