./pngout "money [www.imagesplitter.net]-0-0.gif" -c6
./pngout "money [www.imagesplitter.net]-0-1.gif" -c6
./pngout "money [www.imagesplitter.net]-0-2.gif" -c6
./pngout "money [www.imagesplitter.net]-0-3.gif" -c6
./pngout "money [www.imagesplitter.net]-0-4.gif" -c6
./pngout "money [www.imagesplitter.net]-0-5.gif" -c6
./pngout "money [www.imagesplitter.net]-0-6.gif" -c6
./pngout "money [www.imagesplitter.net]-0-7.gif" -c6
./pngout "money [www.imagesplitter.net]-0-8.gif" -c6
./pngout "money [www.imagesplitter.net]-0-9.gif" -c6
./pngout "money [www.imagesplitter.net]-1-0.gif" -c6
./pngout "money [www.imagesplitter.net]-1-1.gif" -c6
./pngout "money [www.imagesplitter.net]-1-2.gif" -c6
./pngout "money [www.imagesplitter.net]-1-3.gif" -c6
./pngout "money [www.imagesplitter.net]-1-4.gif" -c6
./pngout "money [www.imagesplitter.net]-1-5.gif" -c6
./pngout "money [www.imagesplitter.net]-1-6.gif" -c6
./pngout "money [www.imagesplitter.net]-1-7.gif" -c6
./pngout "money [www.imagesplitter.net]-1-8.gif" -c6
./pngout "money [www.imagesplitter.net]-1-9.gif" -c6
./pngout "money [www.imagesplitter.net]-2-0.gif" -c6
./pngout "money [www.imagesplitter.net]-2-1.gif" -c6
./pngout "money [www.imagesplitter.net]-2-2.gif" -c6
./pngout "money [www.imagesplitter.net]-2-3.gif" -c6
./pngout "money [www.imagesplitter.net]-2-4.gif" -c6
./pngout "money [www.imagesplitter.net]-2-5.gif" -c6
./pngout "money [www.imagesplitter.net]-2-6.gif" -c6
./pngout "money [www.imagesplitter.net]-2-7.gif" -c6
./pngout "money [www.imagesplitter.net]-2-8.gif" -c6
./pngout "money [www.imagesplitter.net]-2-9.gif" -c6
./pngout "money [www.imagesplitter.net]-3-0.gif" -c6
./pngout "money [www.imagesplitter.net]-3-1.gif" -c6
./pngout "money [www.imagesplitter.net]-3-2.gif" -c6
./pngout "money [www.imagesplitter.net]-3-3.gif" -c6
./pngout "money [www.imagesplitter.net]-3-4.gif" -c6
./pngout "money [www.imagesplitter.net]-3-5.gif" -c6
./pngout "money [www.imagesplitter.net]-3-6.gif" -c6
./pngout "money [www.imagesplitter.net]-3-7.gif" -c6
./pngout "money [www.imagesplitter.net]-3-8.gif" -c6
./pngout "money [www.imagesplitter.net]-3-9.gif" -c6
./pngout "money [www.imagesplitter.net]-4-0.gif" -c6
./pngout "money [www.imagesplitter.net]-4-1.gif" -c6
./pngout "money [www.imagesplitter.net]-4-2.gif" -c6
./pngout "money [www.imagesplitter.net]-4-3.gif" -c6
./pngout "money [www.imagesplitter.net]-4-4.gif" -c6
./pngout "money [www.imagesplitter.net]-4-5.gif" -c6
./pngout "money [www.imagesplitter.net]-4-6.gif" -c6
./pngout "money [www.imagesplitter.net]-4-7.gif" -c6
./pngout "money [www.imagesplitter.net]-4-8.gif" -c6
./pngout "money [www.imagesplitter.net]-4-9.gif" -c6
./pngout "money [www.imagesplitter.net]-5-0.gif" -c6
./pngout "money [www.imagesplitter.net]-5-1.gif" -c6
./pngout "money [www.imagesplitter.net]-5-2.gif" -c6
./pngout "money [www.imagesplitter.net]-5-3.gif" -c6
./pngout "money [www.imagesplitter.net]-5-4.gif" -c6
./pngout "money [www.imagesplitter.net]-5-5.gif" -c6
./pngout "money [www.imagesplitter.net]-5-6.gif" -c6
./pngout "money [www.imagesplitter.net]-5-7.gif" -c6
./pngout "money [www.imagesplitter.net]-5-8.gif" -c6
./pngout "money [www.imagesplitter.net]-5-9.gif" -c6

